version: "3.1"

services:
  db:
    image: postgres
    container_name: gobarber_postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_DB: gobarber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    container_name: gobarber_adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: "pepa-linha"
